import 'dart:convert';
import 'dart:html' as html;
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import '../brand.dart';
import 'login_screen.dart';

class BillingScreen extends StatefulWidget { const BillingScreen({super.key}); @override State<BillingScreen> createState() => _BillingScreenState(); }
class _BillingScreenState extends State<BillingScreen> {
  Map<String, dynamic>? _data; List<dynamic> _plans=[]; bool _loading = true;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { final token = (await SharedPreferences.getInstance()).getString('jwt_token'); try { final results=await Future.wait([http.get(Uri.parse('$kApiBaseUrl/v1/billing/status'),headers:{'Authorization':'Bearer $token'}),http.get(Uri.parse('$kApiBaseUrl/v1/billing/plans'),headers:{'Authorization':'Bearer $token'})]); if(results[0].statusCode==200)_data=jsonDecode(results[0].body); if(results[1].statusCode==200)_plans=jsonDecode(results[1].body); } finally { if(mounted)setState(()=>_loading=false); } }
  Future<void> _checkout() async { final plan = await showDialog<dynamic>(context:context,builder:(c)=>AlertDialog(backgroundColor:BonsoBrand.surface,title:const Text('Contratar o cambiar plan',style:TextStyle(color:Colors.white)),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:_plans.map((p)=>ListTile(title:Text(p['nombre'],style:const TextStyle(color:Colors.white)),subtitle:Text('${p['precio_mensual']} ${p['moneda']} · ${p['tokens_mensuales']} tokens',style:const TextStyle(color:Colors.white70)),onTap:()=>Navigator.pop(c,p))).toList())),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancelar'))])); if(plan==null)return; final token=(await SharedPreferences.getInstance()).getString('jwt_token'); final r=await http.post(Uri.parse('$kApiBaseUrl/v1/billing/checkout/${plan['id_plan']}'),headers:{'Authorization':'Bearer $token'}); if(r.statusCode==200){final url=jsonDecode(r.body)['checkout_url']; if(url!=null)html.window.open(url,'_blank');} else if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('No se pudo abrir el cobro: ${r.body}')));} }
  @override Widget build(BuildContext context) { final d=_data; final used=(d?['tokens_consumidos']??0) as int; final limit=(d?['tokens_mensuales']??0) as int; return Scaffold(backgroundColor:BonsoBrand.ink,appBar:AppBar(title:const Text('Plan y facturación')),body:_loading?const Center(child:CircularProgressIndicator()):Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(d?['plan']??'Sin plan',style:const TextStyle(fontSize:28,color:Colors.white,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text('Estado: ${d?['subscription_status']??'none'}',style:const TextStyle(color:BonsoBrand.aqua)),const SizedBox(height:28),Text('Uso mensual: $used / $limit tokens',style:const TextStyle(color:Colors.white70)),const SizedBox(height:10),LinearProgressIndicator(value:limit>0?(used/limit).clamp(0,1):0,color:BonsoBrand.aqua,backgroundColor:BonsoBrand.surfaceRaised),const SizedBox(height:28),Text('Precio: ${d?['precio_mensual']??0} ${d?['moneda']??'CLP'} / mes',style:const TextStyle(color:Colors.white,fontSize:18)),const Spacer(),ElevatedButton.icon(onPressed:_checkout,icon:const Icon(Icons.credit_card),label:const Text('Gestionar suscripción'),style:ElevatedButton.styleFrom(backgroundColor:BonsoBrand.lime,foregroundColor:Colors.black)),const SizedBox(height:12),const Text('Los cobros son procesados de forma segura por Mercado Pago.',style:TextStyle(color:Colors.white54))]))); }
}
