"""Init_schema

Revision ID: 321c35a47b37
Revises: 
Create Date: 2026-09-12 02:52:08.275060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321c35a47b37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saas_planes',
    sa.Column('id_plan', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_plan', sa.String(length=50), nullable=False),
    sa.Column('permite_erp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_plan'),
    sa.UniqueConstraint('nombre_plan')
    )
    op.create_table('saas_tenants',
    sa.Column('id_tenant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_organizacion', sa.String(length=150), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_plan'], ['saas_planes.id_plan'], ),
    sa.PrimaryKeyConstraint('id_tenant')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tenant', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_tenant'], ['saas_tenants.id_tenant'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tenant', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil_jarvis', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_tenant'], ['saas_tenants.id_tenant'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tenant', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=8), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_tenant'], ['saas_tenants.id_tenant'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('patente')
    )
    op.create_table('ordenes_trabajo',
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tenant', sa.Integer(), nullable=False),
    sa.Column('folio_ot', sa.String(length=20), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('diagnostico_ia', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_tenant'], ['saas_tenants.id_tenant'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_orden'),
    sa.UniqueConstraint('folio_ot')
    )
    op.create_table('pagos_mercado_pago',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tenant', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_transaccion_mp', sa.String(length=100), nullable=False),
    sa.Column('monto_pagado', sa.Integer(), nullable=False),
    sa.Column('estado_pago', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_trabajo.id_orden'], ),
    sa.ForeignKeyConstraint(['id_tenant'], ['saas_tenants.id_tenant'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pago'),
    sa.UniqueConstraint('id_transaccion_mp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_mercado_pago')
    op.drop_table('ordenes_trabajo')
    op.drop_table('vehiculos')
    op.drop_table('usuarios')
    op.drop_table('clientes')
    op.drop_table('saas_tenants')
    op.drop_table('saas_planes')
    # ### end Alembic commands ###
